### ISSUE TITLE
关于Halo插件“文本编辑器”不支持“数据包图”的问题

### ISSUE THREAD

**Issue by 28778** [xinkeng0/xinkeng0#1]
您好，很感谢对此项目的维护，但我在使用此插件的时候遇到了一些问题：
1.我不知道如何切换它的主题。

2.此插件好像不支持“数据包图”功能，图片如下：
![image](https://github.com/user-attachments/assets/6a94dbb3-7627-466f-9d6d-5a5d873c0a32)
在Mermid的官方文档里，是支持这个功能的，图片如下。（我是一名计算机网络学习者，非常需要此功能）
![image](https://github.com/user-attachments/assets/b88f5f74-6841-4cb1-b7cd-8100618558b3)
如果您能修复此问题，不甚感激！！！！！！！！！！！！！！！！！！！！！！！！！！！！
邮箱shefr_plfd2333@foxmail.com    -Addiandroky

**Comment by xinkeng0** [comment]
1.我不知道如何切换它的主题。
试试这个，单独配置一个图表 https://mermaid.js.org/config/theming.html#diagram-specific-themes
2.此插件好像不支持“数据包图”功能
[mermaid-packet-diagram](https://mermaid.js.org/syntax/packet.html) 需要11版本，插件目前是10版本。

**Comment by xinkeng0** [comment]
此插件的新版本应已支持“数据包图”
